### ISSUE TITLE
HisenZhang 的博客不开HTTPS，还把课程资料发在上面！

### ISSUE THREAD

**Issue by maomihz** [HFLS/ChatRoom#5]
现在整个互联网都在发展HTTPS，没有HTTPS的网站被联通劫持！（不仅是联通）

请求我们所有社团成员对此引起重视，社长不对互联网的发展引起重视！
在现在这年代，证书都不要钱的（Let's Encrypt），社长虽说Linux为黑客精髓，却不懂如何配置HTTPS，关键是完全没有对此事引起重视。

HTTPS还有提高Google搜索位置的作用。

在此请求 @HisenZhang 对于个人网站开启全站HTTPS！希望 @UltraSilicon 同样引起重视！

已知的没有HTTPS的域名：
dev-a.tk
hflsdev.org
hisen.tk
hisenz.com

所有以上网站开启全站HTTPS后请将此issue关闭。

**Comment by HisenZhang** [comment]
dev-a.tk我准备关闭了。hisen.tk将于明年二月底左右过期。剩下两个期中考完就动手。

**Comment by maomihz** [comment]
快要关闭了的也要开呀，至少做个跳转
我这个 废弃域名也是可以HTTPS
https://lk1.bid/
这个也是可以访问的，不会证书错误，就是个跳转

**Comment by maomihz** [comment]
感谢对互联网安全的支持。
